# Generated by Django 2.2.5 on 2019-10-23 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmazingRaceApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='game',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='live',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='game',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
    ]
