# Generated by Django 2.2.5 on 2019-10-10 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmazingRaceApp', '0002_game_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='order',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='game',
            name='code',
            field=models.TextField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='profilepictures',
            name='picture',
            field=models.ImageField(blank=True, upload_to='profile_picture'),
        ),
        migrations.DeleteModel(
            name='LocationGame',
        ),
    ]
