# Generated by Django 2.2.5 on 2019-10-26 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmazingRaceApp', '0002_auto_20191023_0538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilepictures',
            name='picture',
            field=models.ImageField(blank=True, default='/profile_picture/default-picture.png', upload_to='profile_picture'),
        ),
    ]
