# Generated by Django 2.2.5 on 2019-10-31 09:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmazingRaceApp', '0003_auto_20191026_0137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.TextField(max_length=20, validators=[django.core.validators.MinLengthValidator(4)]),
        ),
        migrations.AlterField(
            model_name='profilepictures',
            name='picture',
            field=models.ImageField(default='/profile_picture/default-picture.png', upload_to='profile_picture'),
        ),
    ]
