# Generated by Django 2.2.5 on 2019-10-31 10:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmazingRaceApp', '0004_auto_20191031_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='clues',
            field=models.TextField(max_length=500, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.TextField(max_length=20, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
    ]
