# Generated by Django 2.2.5 on 2019-10-31 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AmazingRaceApp', '0005_auto_20191031_1000'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProfilePictures',
        ),
    ]
